extraction:
  cpp:
    prepare:
      packages:
        - libssl-dev
      after_paepare:
        - rm -f CMakeLists.txt
        - ./buildconf
      configure:
        command: ./configure --enable-ares --with-libssh2 --with-gssapi --with-librtmp --with-libmetalink
